In [4]:
%pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [13]:
def bubble_sort(a):
    n = len(a)
    if n <= 1:
        return
        # return a
    else:
        step = 1
        while step < n:
            for i in range(n-step):
                if a[i] > a[i+1]:
                    temp = a[i]
                    a[i] = a[i+1]
                    a[i+1] = temp
            step += 1
        # return a


def select_sort(a):
    n = len(a)
    if n <= 1:
        pass
    else:
        for i in range(0, n-1):
            min = i
            for j in range(i+1, n):
                if a[j] < a[min]:
                    min = j
            temp = a[i]
            a[i] = a[min]
            a[min] = temp


def insert_sort(a):
    n = len(a)
    if n <= 1:
        return

    for i in range(1, n):
        now = a[i]
        position = 0
        for j in range(i-1, -1, -1):
            if a[j] > now:
                a[j+1] = a[j]
            else:
                position = j+1
                break
        a[position] = now


def shell_sort(a):
    n = len(a)
    if n <= 1:
        return
    
    d = int(sqrt(n))
    while d >= 1:
        for i in range(d):
            subarray = a[i:n:d]
            insert_sort(subarray)
        d = int(d/2)


def merge_sort(a, low, high):
    if low == high-1:
        if a[low] > a[high]:
            temp = a[low]
            a[low] = a[high]
            a[high] = temp
    elif low >= high:
        pass
    else:
        mid = int((low+high)/2)
        merge_sort(a, low, mid)
        merge_sort(a, mid+1, high)


def quick_sort(a, low, high):

    if low>= high or low > len(a)-1:
        return
    ax = a[low]
    i = low
    j = high
    while(i < j):
        while a[j] >= ax and i < j:
            j -= 1

        while a[i] <= ax and i < j:
            i += 1
        temp = a[i]
        a[i] = a[j]
        a[j] = temp

    a[low] = a[i]
    a[i] = ax

    quick_sort(a, low, i-1)
    quick_sort(a, i+1, high)


def qsort_nonrecur(a, low, high):
    index_stacks = []
    index_stacks.append((low, high))
    while len(index_stacks) != 0:
        left, right = index_stacks.pop()
        
        if left >= right or left > len(a)-1:
            pass
        else:
            ax = a[left]
            i = left
            j = right
            while(i < j):
                while a[j] >= ax and i < j:
                    j -= 1

                while a[i] <= ax and i < j:
                    i += 1
                temp = a[i]
                a[i] = a[j]
                a[j] = temp
                
            a[left] = a[i]
            a[i] = ax

            index_stacks.append((left, i-1))
            index_stacks.append((i+1, high))


def mergesort(a, low, high):
    pass

In [23]:
x=np.random.permutation(range(100))
x

array([ 7,  0, 17, 91, 78, 26, 23, 14,  2, 59, 36, 76,  9, 50, 61, 90, 57,
       33, 30, 85, 29, 70, 45, 48, 47, 69, 54, 72, 81, 40, 99, 67, 39, 75,
       73, 96, 93, 62, 77, 97, 88, 65,  4,  6, 74, 41, 84, 79, 35, 15,  8,
       95, 80, 49, 51, 11, 68, 83, 98,  3, 34, 27, 58, 55, 20, 43, 10, 38,
       53, 87, 52, 24, 32, 16, 86, 63, 82, 25, 89, 66,  5, 19, 42, 46, 44,
       64, 71, 56, 92, 12, 18, 60, 94, 21, 22, 28, 13, 37,  1, 31])

In [20]:
quick_sort(x,0,len(x)-1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
quick_sort_nonrec(x,0,len(x)-1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [460]:
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

[1, 2]